# Generated by Django 5.0.14 on 2026-01-17 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité maximale')),
                ('current_registrations', models.PositiveIntegerField(default=0, verbose_name='Inscriptions actuelles')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('CLOSED', 'Fermé'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=15, verbose_name='Statut')),
                ('image_consent_required', models.BooleanField(default=False, verbose_name='Consentement image requis')),
                ('barcode_prefix', models.CharField(blank=True, max_length=20, verbose_name='Préfixe code-barres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Photo d'événement",
                'verbose_name_plural': "Photos d'événements",
                'db_table': 'event_photos',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REGISTERED', 'Inscrit'), ('CHECKED_IN', 'Présent'), ('CANCELLED', 'Annulé')], default='REGISTERED', max_length=15, verbose_name='Statut')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Code-barres')),
                ('image_consent', models.BooleanField(default=False, verbose_name='Consentement image')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Arrivé le')),
            ],
            options={
                'verbose_name': 'Inscription à un événement',
                'verbose_name_plural': 'Inscriptions aux événements',
                'db_table': 'event_registrations',
            },
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Retour d'événement",
                'verbose_name_plural': "Retours d'événements",
                'db_table': 'event_feedback',
            },
        ),
    ]
