# Generated by Django 5.0.14 on 2026-01-17 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Objectif financier')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant actuel')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campagne de financement',
                'verbose_name_plural': 'Campagnes de financement',
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='TaxReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('year', models.PositiveIntegerField(verbose_name="Année d'imposition")),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('organization_number', models.CharField(max_length=50, verbose_name="Numéro d'organisme")),
                ('pdf_path', models.FileField(upload_to='receipts/%Y/', verbose_name='Fichier PDF')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Émis le')),
            ],
            options={
                'verbose_name': 'Reçu fiscal',
                'verbose_name_plural': 'Reçus fiscaux',
                'db_table': 'tax_receipts',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='CAD', max_length=3, verbose_name='Devise')),
                ('type', models.CharField(choices=[('COTISATION', 'Cotisation'), ('ONE_TIME', 'Don ponctuel'), ('RECURRING', 'Don récurrent')], max_length=20, verbose_name='Type')),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Carte de crédit (Stripe)'), ('INTERAC', 'Interac'), ('PAYPAL', 'PayPal'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], max_length=20, verbose_name='Méthode de paiement')),
                ('payment_id', models.CharField(blank=True, max_length=255, verbose_name='ID de transaction')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('receipt_issued', models.BooleanField(default=False, verbose_name='Reçu émis')),
                ('donated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du don')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='finance.campaign', verbose_name='Campagne')),
            ],
            options={
                'verbose_name': 'Don / Cotisation',
                'verbose_name_plural': 'Dons / Cotisations',
                'db_table': 'donations',
                'ordering': ['-donated_at'],
            },
        ),
    ]
