# Generated by Django 5.0.14 on 2026-01-17 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='taxreceipt',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='finance.taxreceipt', verbose_name='Reçu fiscal'),
        ),
    ]
