# Generated by Django 5.0.14 on 2026-01-17 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('category', models.CharField(choices=[('RELIGIOUS', 'Religieuse'), ('CULTURAL', 'Culturelle'), ('ADMINISTRATIVE', 'Administrative'), ('GENERAL', 'Générale')], default='GENERAL', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publiée'), ('EXPIRED', 'Expirée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'db_table': 'announcements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(verbose_name='Heure de fin')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('category', models.CharField(choices=[('PRAYER', 'Prière / Religieux'), ('COURSE', 'Cours'), ('MEETING', 'Réunion'), ('CELEBRATION', 'Célébration'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Événement calendrier',
                'verbose_name_plural': 'Événements calendrier',
                'db_table': 'calendar_events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu (HTML/Texte)')),
                ('template_id', models.CharField(blank=True, max_length=100, verbose_name='ID Modèle')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='Nombre de destinataires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Infolettre',
                'verbose_name_plural': 'Infolettres',
                'db_table': 'newsletters',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], max_length=10, verbose_name='Canal')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
