# Generated by Django 5.0.14 on 2026-01-17 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la ressource')),
                ('type', models.CharField(choices=[('ROOM', 'Salle'), ('EQUIPMENT', 'Matériel'), ('VEHICLE', 'Véhicule'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité')),
                ('is_available', models.BooleanField(default=True, verbose_name='Est disponible')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(verbose_name='Heure de fin')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='resources.resource', verbose_name='Ressource')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservations',
                'ordering': ['-start_time'],
            },
        ),
    ]
